site_name: Kopen Data Builder
site_description: A universal CLI and SDK tool for transforming Korean public data into Hugging Face-compatible datasets.
site_author: Yeongseon Choe
repo_url: https://github.com/yeongseon/kopen-data-builder  # 올바른 저장소 URL로 수정

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.annotate

nav:
  - Home: index.md
  - Development Guide: development.md
  - Release Notes: release.md
  - Usage Guide: document.md
  - API Reference:
      - CLI: reference/cli.md

docs_dir: docs

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src"]

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
